name: Deploy Resume to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Blob Storage
      uses: azure/CLI@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload-batch --account-name resumevbaez --auth-mode login -d '$web' -s . --overwrite